name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_ubuntu_x11:
    name: Build Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Build
        run: |
          cmake .
          make

  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Build
        env:
          TARGET_PLATFORM: windows
        run: |
          cmake .
          cmake --build .

  build_macOS:
    name: Build Mac
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"  
      - name: Build
        run: |
          curl -O https://sdk.lunarg.com/sdk/download/latest/mac/vulkan_sdk.dmg  
          hdiutil attach vulkan_sdk.dmg 
          /Volumes/VulkanSDK/InstallVulkan.app/Contents/MacOS/InstallVulkan in -d --am --al --dl -aa -da --ns -c
          cd /Users/runner/VulkanSDK/1.3.250.1/
          python install_vulkan.py
          cd ../../
          brew --prefix libomp 
          cmake -G "Xcode" -DOpenMP_C_FLAGS=/usr/local/opt/libomp -DOpenMP_omp_LIBRARY=/usr/local/opt/libomp -DOpenMP_CXX_FOUND=/usr/local/opt/libomp
          cmake --build .
